### ISSUE TITLE
json5 package dependency 

### ISSUE THREAD

**Issue by roderickhsiao** [yahoo/ycb-config#10]
we currently locked the version in ``0.2.0``, would be good if we can be more flexible for minor version upgrade so that down stream user will not need to download multiple version of package.

https://github.com/aseemk/json5 (currently on ``0.4.0``)

**Comment by caridy** [comment]
:+1: Pull request is welcome!

**Comment by roderickhsiao** [comment]
https://github.com/yahoo/ycb-config/pull/11
