### ISSUE TITLE
Request for promise usage

### ISSUE THREAD

**Issue by realdennis** [yahoo/ycb-config#21]
Hi, I think if we have the promise usage, it might be good to develop without nested callback, but I found that it was removed promise long years ago[1], is there any concern about?

Maybe we could have some additional interface like `ycbConfig.promises` without breaking the original usage.

[1] https://github.com/yahoo/ycb-config/commit/f585336216ccd0c547f1dc0b1fa15da8fc507ace

**Comment by redonkulus** [comment]
Fixed via #24
